import Head from "next/head";
import Sidebar from "../components/Sidebar";
import Modal from "../components/Modal";
import { useTranslationContext } from "../store/context";

export default function Home() {
  const { state, dispatch } = useTranslationContext();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-blue-700">
        <Sidebar />
      </div>
      <Modal
        onClose={() => dispatch({ type: "showModal", payload: false })}
        show={state.showModal}
      >
        Hello from the modal!
      </Modal>
    </>
  );
}
